# Generated by Django 4.2.1 on 2023-05-19 01:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cargos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cargo')),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('pr_address', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rep_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_as_employee', to='base.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('supervisors', models.ManyToManyField(related_name='reports_as_supervisor', to='base.employee')),
            ],
            options={
                'db_table': 'reportes',
            },
        ),
        migrations.CreateModel(
            name='Photo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_link2', models.ImageField(blank=True, null=True, upload_to='images2/')),
                ('ph_date2', models.DateField(default=django.utils.timezone.now)),
                ('ph_desc2', models.CharField(blank=True, max_length=999, null=True)),
                ('reports2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.report')),
            ],
            options={
                'db_table': 'photos2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_link', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ph_date', models.DateField(default=django.utils.timezone.now)),
                ('ph_desc', models.CharField(blank=True, max_length=999, null=True)),
                ('ph_user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ph_observation', models.CharField(blank=True, max_length=5000, null=True)),
                ('reports', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.report')),
            ],
            options={
                'db_table': 'photos',
                'managed': True,
            },
        ),
    ]
