# Generated by Django 4.2.1 on 2023-05-20 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_photo2_ph_observation2'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo2',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.photo'),
        ),
    ]
