# Generated by Django 4.2.1 on 2023-05-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_emailgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'charges',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cer_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'certifications',
                'managed': True,
            },
        ),
    ]
