# Generated by Django 4.2.1 on 2023-05-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cargos_certifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cargos',
            new_name='Charges',
        ),
    ]
